// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function WriteToCB(arg1) {
  return window['go']['main']['App']['WriteToCB'](arg1);
}
