// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';

export function GetConfig():Promise<common.Config>;

export function GetHistory():Promise<Array<common.ItemWithID>>;

export function UpdateConfig(arg1:common.Config):Promise<void>;

export function WriteToCB(arg1:number):Promise<void>;
