services:
  db:
    container_name: clipboard-share-db
    image: postgres:alpine
    restart: always
    env_file: .env
    networks:
      - clipboard-share-network
  server:
    container_name: clipboard-share-server
    build:
      context: .
    restart: always
    env_file: .env
    networks:
      - clipboard-share-network
    ports:
      - '8080:8080'
    depends_on:
      - db

networks:
  clipboard-share-network:
    driver: bridge