services:
  db:
    container_name: clipboard-share-db
    image: postgres:alpine
    restart: always
    env_file: .env
    networks:
      - clipboard-share-network
  server:
    container_name: clipboard-share-server
    build:
      context: .
    restart: always
    env_file: .env
    networks:
      - clipboard-share-network
    depends_on:
      - db
  proxy:
    container_name: clipboard-share-proxy
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/:/etc/nginx/ssl:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - clipboard-share-network
    depends_on:
      - server

networks:
  clipboard-share-network:
    driver: bridge