@baseUrl = http://localhost:8080

### Check server health
# @name HealthCheck
GET {{baseUrl}}/health

### Get user's items without data
# @name GetItemsWithoutData
GET {{baseUrl}}/items
Authorization: Basic YXNkOmFzZA==

### Get user's item with data by ID
# @name GetItemWithDataByID
GET {{baseUrl}}/items/5
Authorization: Basic YXNkOmFzZA==

### Add a new clipboard item
# @name AddNewItem
POST {{baseUrl}}/items
Content-Type: application/json

{
    "PersonID": 1,
    "Type": {
        "ClipboardType": "X11",
        "valid": true
        },
    "Content": "test",
    "Data": [
        {
            "Format": "STRING",
            "Data": "test"
        }
    ]
}

###