// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: test.sql

package db

import (
	"context"
)

const test = `-- name: Test :one
select 'test'
`

func (q *Queries) Test(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, test)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
